language: python
stages:
  - lint
  - test
  - deploy
python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - THIS_REPO="${TRAVIS_REPO_SLUG#*/}"
    - OWNER=YakDriver
    - RELEASE_BRANCH=master
    - RELEASE_VERSION=$(grep -E '^current_version' $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //')
    - PRIOR_VERSION=$(git describe --abbrev=0 --tags)

stage: test
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install -r requirements/pip.txt
  - pip install -r requirements/test.txt
  - pip install --editable .
script:
  - pytest
jobs:
  include:
    - stage: lint
      python: 3.6
      install:
        - pip install -r requirements/pip.txt
        - pip install -r requirements/lint.txt
        - pip install --editable .
      script:
        - pylint compatibleversion
        - pylint tests/*py
        - flake8
    - stage: test
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version 3.7.4
      install:
        - python -m pip install -r requirements/pip.txt
        - python -m pip install -r requirements/test.txt
        - pip install --editable .
    - stage: deploy
      if: branch = env(RELEASE_BRANCH) AND type != pull_request
      python: 3.6
      env:
        - JOB="Deploy to Test PyPI"
      install: skip
      script:
        - sed -i -E "s/^(version = )(.*)/\1\2.$TRAVIS_BUILD_NUMBER/" $TRAVIS_BUILD_DIR/setup.cfg
      deploy:
        - provider: pypi
          server: https://test.pypi.org/legacy/
          distributions: sdist bdist_wheel
          user: __token__
          password:
            secure: "P2XDhceBF2AzxzJ7Jwnw7tsXntH7GMAXBLEZz21wu6agIHg37/qaPOiF4FdFqSP+E6TeaatDsyL+rgB1cesd4008VgAxfUu61Zhuqsk/+/I49Iz6MeXF+Q3hNN2pbosHr+Vis6gamnw+4ofM99S+A/v3gx60Uuo+Kgh8AUeHdgGYGCz4eg9MdL6yHBpLmZfosO41XG34E39s5c9GuPZ6xLBOMxdP3bIGUXlEPY9tV92+XPSz8TsYsM/3Xq5kE0ih7mD4jH4eyNQedNGNwEeqBcNkzIBKALxFcB7gHI/CYzR5LKp/iRHlfVOFcJeCa8gfYgpWHuM35w2FXMxNQ2ui09lWTnG5Ujw7JHDU+kKrXNKvcT+apSTfTShINoKZZdhbQxj5z5sezq1Z6nOvcl0D/KBabw55/KUVjP5VuwfimP45z8F1Zire1PvYNQ4G4v9k4ZJiEVjwwiDfPUwGeiUe4tG9R9V97/5uZzTG+87G9T7PUldZZyrM3t4yeMKwsDLnfmMzPajGelJVpnIGe/WFp9y9emI7gFd+eSj/sc9resvGC5v58I18ffSO3s4Lzoh72HJkMo9GKfyil2iZIrt8it/Af1gOWHOh9lZO5E+eam0QhOCHTugSApa6jS/zn+i5XLxs9+4EjLoaO8u9rJRDfJiieLy+3ArYroBYCv+gn1k="
          skip_cleanup: true
          skip_upload_docs: true
          on:
            branch: $RELEASE_BRANCH
            condition: '"$PRIOR_VERSION" = "$RELEASE_VERSION"'
    - stage: deploy
      if: branch = env(RELEASE_BRANCH) AND type != pull_request
      python: 3.6
      env:
        - JOB="Deploy to GitHub Releases"
        - RELEASE_BODY="* [$THIS_REPO v$RELEASE_VERSION CHANGELOG](https://github.com/$OWNER/$THIS_REPO/compare/$PRIOR_VERSION...$RELEASE_VERSION)"
      install: skip
      script:
        - echo RELEASE_BODY=$RELEASE_BODY
      deploy:
        - provider: releases
          name: $RELEASE_VERSION
          tag_name: $RELEASE_VERSION
          target_commitish: $TRAVIS_COMMIT
          body: $RELEASE_BODY
          draft: false
          skip_cleanup: true
          api_key:
            secure: EAzZCo6RRcdheI4/uEz6RiAqySWUp77g6sOirtbV3kPoJC0HA5ws1+qzWkMNKghQMo6y1eBxwU/tv6CkjXGygZKrs/ZpgfjTtd0Mqe12HN8+0JX9MV/UHpzh3M10QthqflpV+WsG0iAyZvlkJnvtXIFHSjTQMedB7EyPdicZniXXBdGbPoJWU2PBbmA0TI5U6ksP+DtXrvNWP9zpQq06mqO0KPH4AhfB2A638fOJWBbDhWH9BukzIJgh6qvpx6601LGX5uGEe+FdEj74Y/UZOZwjCkVzFDX/Cm+6wS9d2WISjAXO5wISltY3swff0kavwywKrezcRATdHh7lJKu2l+kWa9hf1gAIyJHIf/0qBOIT/TqfVfpKWZ3/VIY4/+OnTIWdUhHGFIliDOduxMPgMzYfp49wU6acIwl67I3FBT9j/SGG6Zsk15Gb9d0nzJvzc7gvwGyba7uPZ807/nYFP4wBXWc14maAbe3sgpL8sCrr6pJby3TNdH97RQpAayIPF9Y2AA5x/MbjVmRQTi93WR5Y5Ov0jdcxFMLgSqKhY93g3CUROiM7HV34vlcYCJUxLiUKCeG7pTIDL6+n660S4Ky933KH2Gf6yoGxVdHMRB58y2aneqdCKoIO0ReqBp8Su6jspF2XcRmYp6hkRMCfo5Msc/lluglVESoTf28wBKU=
          on:
            branch: $RELEASE_BRANCH
            condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
    - stage: deploy
      if: tag is present
      python: 3.6
      env:
        - JOB="Deploy to PyPI"      
      install: skip
      script: skip
      deploy:
          - provider: pypi
            distributions: sdist bdist_wheel
            user: plus3it
            password:
              secure: k8/KhImebgJIvSYUfhNVwKGj+AvI24hxztG/MIlBA9alXIlaaw+/UYAwkvZlNWP3bicr3iEem4erGfMd3SZnc1eNlGeKFuKKn7pvqB2h6wQrFPuEaCrr6TZCZsLOE9qrCVpKxRx2squ56syhfhOkBCwgVs2agwcA4kcOK/XRld/cDXm5CgsZgnlXqVJ/Lij+TLSPl37C73lB3EZntEpXyYRyJ4qBpU0yXOC1zGC1uJyF5fycGk2aHthGcoxZKn/YpW4PeF3alAgi3uE2EfkgHk5rTXaw+pBAeVltyKW8ZpIhj15zkDCUwbeRtOtay21JdUWrY2onc5F3xhCWqDQUWXyS+AdF18DYxxGbHlDETHEms1DBbsIDU/4bDVQrSzsFlRBNvzuitJHxplateZWYUBbLkeYofli6gHxhepl4uFngSyfoAC5OnSXa2hxBXkB1atfDOTEZO0yBN1mk6BuGjqJwCl/kIYU6tRtSzRo0h1jiX7QDMlI97jvNc4M6kvTb6h6m7bt6fa2z4cUnydZg2sBWmlRai0ruOIdAiKQdo8Lxg5YSZE2/F0JGIQicrc9LSbdIoiCqEXfrFRSSiEWLc+APSx2K4+CrgkCVDxhpNvuu5V1hbwjHmG2eZwUKnxEoH6jXbUAokKe0QcHqtJCRg6n+H+aIHoZhbOs/OCtoJlM=
            skip_upload_docs: true
            on:
              tags: true
