name: Cut release automatically

on:
  schedule:
    - cron: "50 2 * * 5"

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Check commits since last release
        id: count-commits
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git describe --tags --abbrev=0
          commits_since=$(git log $(git describe --tags --always --abbrev=0)..HEAD --oneline | wc -l)
          echo "Commits since last release: $commits_since"
          if [ "${commits_since}" == "0" ]; then
            echo "No release needed"
            exit 1
          else
            echo "Release needed"
          fi

  bump-version:
    needs: check-changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: |
          pip install -r $GITHUB_WORKSPACE/requirements/release.txt
          newver=$(bumpversion --dry-run --list patch | grep new_version= | sed -r s,"^.*=",,)
          echo "New version will be ${newver}"
          git config --global user.email "${EMAIL}"
          git config --global user.name "$(dirname ${REPO_SLUG})"
          git remote set-url origin "https://$(dirname ${REPO_SLUG}):${GITHUB_TOKEN}@github.com/${REPO_SLUG}.git"
          git checkout -b autorelease/$newver
          bumpversion patch
          git add .
          git commit -m "Release $newver"
          git push --set-upstream origin autorelease/$newver
          git status
        env:
          EMAIL: ${{ secrets.EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_SLUG: ${{ github.repository }}
