name: Cut release automatically

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check commits since last release
        id: count-commits
        run: |
          date
          git fetch --all
          commits_since=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline | wc -l)
          echo "Commits since last release: $commits_since"
          if [ "${commits_since}" == "0" ]
            then
              echo "No release needed!"
              exit 1
          fi

  bump-version:
    needs: check-changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: This bumps the version
        run: echo This is the script part
